# Preprocessing Data for NLP Tasks

## Setup

In [1]:
!python --version

Python 3.12.4

In [2]:
!cat requirements.txt

# Python 3.12.x
pandas==2.3.3
numpy==1.26.4
matplotlib==3.10.6
seaborn==0.13.2
wordcloud==1.9.4
nltk==3.9.2
spacy==3.8.9
textblob==0.19.0
scikit-learn==1.7.2
bertopic==0.17.3
pyLDAvis==3.4.1
gensim==4.4.0

In [3]:
!python -m pip install -q -r requirements.txt

In [4]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 34.7 MB/s eta 0:00:0000:010:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

### Imports

In [5]:
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from bertopic import BERTopic
import pandas as pd
from nlp import (
    group_topics_lda,
    get_topic_lda,
    visualize_topics_lda,
    remove_stopwords,
    preprocess_data
)

2025-11-30 12:14:18.351525: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-30 12:14:18.382818: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1764522858.403335  148857 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1764522858.408677  148857 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-11-30 12:14:18.443145: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

[nltk_data] Downloading package stopwords to /home/ballen/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

### Configurations

In [6]:
data_path = '../data/cleaned_ntsb.csv'

In [7]:
pd.set_option('display.max_columns', None)

## Load Data

In [8]:
df = pd.read_csv(data_path, low_memory=False)
df.shape

(87951, 47)

In [9]:
df.head()

,event_id,event_date,investigation_type,country,aircraft_damage,aircraft_category,make,model,amateur_built,number_of_engines,engine_type,far_description,schedule,purpose_of_flight,total_fatal_injuries,total_serious_injuries,total_minor_injuries,total_uninjured,weather_condition,broad_phase_of_flight,analysis,analysis_clean,city,longitude,latitude,address,geometry,place,number_of_seats,type_aircraft,type_engine,total_person,far_description_factorized,schedule_factorized,purpose_of_flight_factorized,make_factorized,model_factorized,year,publication_year,month,publication_month,day,publication_day,date_difference,publication_month_name,event_month_name,season
0,20001218X45444,1948-10-24,Accident,United States,Destroyed,fixed wing single engine,stinson,108-3,No,1,reciprocating,part 91: general aviation,UNK,Personal,2,0,0,0,UNK,Cruise,"ON OCTOBER 24, 1948, THE PILOT DEPARTED A PRIV...",on october the pilot departed a private airstr...,moose creek,-147.160665,64.713512,"Moose Creek, Fairbanks North Star, Alaska, Uni...",POINT (-147.1606646266588 64.7135123),mountain,4,4,1,2,1,2,0,0,0,1948,2001,10,8,24,24.0,26,August,October,Fall
1,20001218X45447,1962-07-19,Accident,United States,Destroyed,weight-shift-control,piper,pa24-180,No,1,reciprocating,part 91: general aviation,UNK,Personal,4,0,0,0,UNK,Unknown,"ON JULY 19, 1962, A COMMERCIAL, NON-INSTRUMENT...",on july a commercial non instrument rated pilo...,bridgeport,-73.188786,41.179269,"Bridgeport, Greater Bridgeport Planning Region...",POINT (-73.1887863 41.1792695),sea,4,7,1,4,1,2,0,1,1,1962,1996,7,9,19,19.0,34,September,July,Summer
2,20061025X01555,1974-08-30,Accident,United States,Destroyed,fixed wing single engine,cessna,172m,No,1,reciprocating,part 91: general aviation,UNK,Personal,3,0,0,1,IMC,Cruise,The private pilot was issued his certificate o...,the private pilot was issued his certificate o...,saltville,-81.762063,36.881503,"Saltville, Smyth County, Virginia, United States",POINT (-81.7620635 36.8815031),sea,4,4,1,3,1,2,0,2,2,1974,2007,8,2,30,30.0,33,February,August,Summer
3,20001218X45448,1977-06-19,Accident,United States,Destroyed,weight-shift-control,rockwell,112,No,1,reciprocating,part 91: general aviation,UNK,Personal,2,0,0,0,IMC,Cruise,The aircraft wreckage was discovered 22 miles ...,the aircraft wreckage was discovered miles sou...,eureka,-124.167375,40.790687,"Eureka, Humboldt County, California, United St...",POINT (-124.1673746 40.7906871),airport,4,7,1,2,1,2,0,3,3,1977,2000,6,12,19,19.0,23,December,June,Summer
4,20041105X01764,1979-08-02,Accident,United States,Destroyed,fixed wing multi engine,cessna,501,No,2,turbo fan,part 91: general aviation,UNK,Personal,1,2,0,0,VMC,Approach,The Safety Board's full report is available at...,the safety board s full report is available at...,canton,-95.864051,32.555664,"Canton, Van Zandt County, Texas, 75103, United...",POINT (-95.8640507 32.555664),airport,8,5,5,3,1,2,0,2,4,1979,1980,8,4,2,2.0,1,April,August,Summer

## Preprocess Narratives
Remove stopwords and special tokens for anlaysis and data visualization purposes.

In [10]:
tokens = remove_stopwords([df['analysis_clean'].iloc[0]])
sent = ' '.join(tokens[0])
print(sent)

october pilot departed private airstrip moose creek ranch two pilots departed time reported encountering heavy snow squalls along selway river headed westbound wreckage found april miles west moose creek selway river drainage mountainous terrain wreckage exhibited characteristics consistent impact trees terrain cruise flight

In [11]:
results = remove_stopwords(df['analysis_clean'].tolist())
len(results)

87951

In [12]:
results = [ ' '.join(result) for result in results ]

In [13]:
print(results[0])

october pilot departed private airstrip moose creek ranch two pilots departed time reported encountering heavy snow squalls along selway river headed westbound wreckage found april miles west moose creek selway river drainage mountainous terrain wreckage exhibited characteristics consistent impact trees terrain cruise flight

In [14]:
df.insert(df.columns.get_loc("analysis_clean")+1, "analysis_preprocessed", results)

In [15]:
df[['analysis_clean', 'analysis_preprocessed']].head(3).values

array([['on october the pilot departed a private airstrip at the moose creek ranch at two other pilots that departed at the same time reported encountering heavy snow squalls along the selway river as they headed westbound the wreckage was found in april miles west of moose creek in the selway river drainage in mountainous terrain the wreckage exhibited characteristics consistent with impact with trees and terrain in cruise flight ',
        'october pilot departed private airstrip moose creek ranch two pilots departed time reported encountering heavy snow squalls along selway river headed westbound wreckage found april miles west moose creek selway river drainage mountainous terrain wreckage exhibited characteristics consistent impact trees terrain cruise flight'],
       ['on july a commercial non instrument rated pilot and three passengers were crossing high mountainous terrain on a night cross country flight subsequently the airplane collided with rising terrain at about feet mean sea level wreckage was found on a degree slope with extensive damage the airplane was reported missing and went undiscovered until august the airplane with human remains was discovered in a remote area of yosemite national park by trail repair personnel the faa and safety board did not have any records of the accident flight the registration number of the airplane had been reassigned to another aircraft in u s park and county sheriff s department personnel conducted a coroner s investigation ',
        'july commercial non instrument rated pilot three passengers crossing high mountainous terrain night cross country flight subsequently airplane collided rising terrain feet mean sea level wreckage found degree slope extensive damage airplane reported missing went undiscovered august airplane human remains discovered remote area yosemite national park trail repair personnel faa safety board records accident flight registration number airplane reassigned another aircraft park county sheriff department personnel conducted coroner investigation'],
       ['the private pilot was issued his certificate one week prior to the accident and he did not possess an instrument rating after extensive discussions flight planning and weather analysis with the pilot the fixed base operator agreed to rent the airplane for the planned cross country flight if the pilot agreed to fly only in day vfr conditions and spend the night at an intermediate stop along his intended course instead the pilot landed at the planned stop refueled and continued his flight over mountainous terrain in night instrument meteorological conditions the wreckage was discovered in mountainous terrain months after the accident the crash site was at an elevation of feet on a mountain with an elevation of feet on the night of the accident the cloud ceilings in the area were measured between feet and feet mean sea level with visibility reduced by rain showers and fog ',
        'private pilot issued certificate one week prior accident possess instrument rating extensive discussions flight planning weather analysis pilot fixed base operator agreed rent airplane planned cross country flight pilot agreed fly day vfr conditions spend night intermediate stop along intended course instead pilot landed planned stop refueled continued flight mountainous terrain night instrument meteorological conditions wreckage discovered mountainous terrain months accident crash site elevation feet mountain elevation feet night accident cloud ceilings area measured feet feet mean sea level visibility reduced rain showers fog']],
      dtype=object)

## Sentiment Analysis

In [16]:
df["sentiment_polarity"] = df["analysis_clean"].apply(lambda x: TextBlob(x).sentiment.polarity)
df["sentiment_category"] = pd.cut(
    df["sentiment_polarity"],
    bins=[-1, -0.05, 0.05, 1],
    labels=["Negative", "Neutral", "Positive"]
)

In [17]:
df[["analysis_clean", "sentiment_polarity", "sentiment_category"]].sample(50, random_state=42)

,analysis_clean,sentiment_polarity,sentiment_category
25609,witnesses observed the acft maneuvering at a l...,-0.019136,Neutral
31738,factual,0.000000,Neutral
5346,after takeoff the plt of the ultralight vehicl...,0.020833,Neutral
85707,the pilot had made two flights on the day of t...,0.024351,Neutral
59785,the airplane was flown by the student and cert...,0.024451,Neutral
22491,the plt landed in a field which he knew contai...,0.214286,Positive
25703,the pilot was landing and bounced twice he rej...,0.158929,Positive
7492,the plt angled in on the final approach at low...,0.095238,Positive
64569,same as factual information,0.000000,Neutral
4293,the pilot was warming the eng for a compressio...,0.037143,Neutral
73557,same as factual information,0.000000,Neutral
1815,before departing st louis mo attempts to resta...,-0.058333,Negative
62735,on october a us airways boeing n uw experience...,0.010777,Neutral
78452,the pilot reported that while on final approac...,0.002778,Neutral
56715,according to the pilot during the take off rol...,0.043386,Neutral
81664,the pilot of the tailwheel equipped airplane r...,-0.033929,Neutral
37925,during departure upon reaching feet altitude a...,0.150000,Positive
35077,the pilot reported he was about feet agl when ...,-0.333333,Negative
11728,the plt was making an apch to rwy at the los a...,0.359524,Positive
59957,same as factual information,0.000000,Neutral
28081,while on final approach to a dirt road the pil...,-0.031111,Neutral
36233,at cst on the helicopter took off on a flight ...,-0.072917,Negative
84407,the pilot completed a multi day cross country ...,-0.085873,Negative
50695,foreign,-0.125000,Negative
86669,unk,0.000000,Neutral
36567,the four engine transport category airplane wa...,0.012778,Neutral
87546,on september about pacific daylight time a bee...,0.046155,Neutral
43431,the hour instrument rated commercial helicopte...,-0.064140,Negative
48767,foreign,-0.125000,Negative
87840,the pilot of the tailwheel equipped airplane r...,0.050265,Positive
21130,the commercial plt was transporting one pax du...,-0.125000,Negative
78511,the government of united kingdom has notified ...,0.000000,Neutral
70454,on february about pacific standard time a euro...,0.010000,Neutral
31287,cattle missed by men on horseback would be spo...,0.000000,Neutral
74855,the pilot reported that he landed the airplane...,-0.007864,Neutral
86949,the pilot reported that after a normal approac...,0.192857,Positive
76342,the australian transport safety bureau atsb ha...,0.000000,Neutral
1543,the pilot reported that he had landed long in ...,0.050000,Positive
37521,the engine sustained a total loss of power at ...,-0.109375,Negative
15910,the pilot was cleared to taxi his airplane int...,0.042857,Neutral
77029,same as factual information,0.000000,Neutral
77045,same as factual information,0.000000,Neutral
63505,the commercial rated pilot was practicing a st...,-0.062500,Negative
77488,same as factual information,0.000000,Neutral
69712,at the conclusion of the pilot s second flight...,0.102679,Positive
57553,according to the pilot during the completion o...,-0.170000,Negative
61962,the instrument rated private pilot departed on...,-0.060000,Negative
40556,the gcbc champion was observed engaged in repe...,0.191446,Positive
69314,the helicopter pilot landed a high skid turbin...,-0.049596,Neutral
43295,while troubleshooting a fire warning indicatio...,0.180000,Positive

### Analyze Sentiment Spread

In [18]:
sentiment_counts = df["sentiment_category"].value_counts()
sentiment_ratio = sentiment_counts / len(df)
sentiment_percent = sentiment_ratio.map(lambda x: f'{x*100:.2f}%')
sentiment_spread = pd.DataFrame({
    'Count': sentiment_counts,
    'Ratio': sentiment_ratio,
    'Percentage': sentiment_percent,
})
sentiment_spread

                    Count     Ratio Percentage
sentiment_category
Neutral             38948  0.442837     44.28%
Positive            27845  0.316597     31.66%
Negative            21158  0.240566     24.06%

**Observation:** Slight imbalance of sentiment categories across the dataset with `Neutral` sentiment representing the majority and `Negative` representing the minority. A perfect balance would have been approximately `33.33%` per category.

In [19]:
# Inspect one report from each category
for category in df["sentiment_category"].unique():
    item = df[df["sentiment_category"] == category].iloc[0]
    narrative = item['analysis_clean']
    event_id = item['event_id']
    event_date = item['event_date']
    print('='*60)
    print(f'Category   : {category}')
    print(f'Event ID   : {event_id}')
    print(f'Event Date : {event_date}')
    print(f'Narrative  : {narrative}')
print('='*60)

============================================================
Category   : Neutral
Event ID   : 20001218X45444
Event Date : 1948-10-24
Narrative  : on october the pilot departed a private airstrip at the moose creek ranch at two other pilots that departed at the same time reported encountering heavy snow squalls along the selway river as they headed westbound the wreckage was found in april miles west of moose creek in the selway river drainage in mountainous terrain the wreckage exhibited characteristics consistent with impact with trees and terrain in cruise flight
============================================================
Category   : Negative
Event ID   : 20001218X45447
Event Date : 1962-07-19
Narrative  : on july a commercial non instrument rated pilot and three passengers were crossing high mountainous terrain on a night cross country flight subsequently the airplane collided with rising terrain at about feet mean sea level wreckage was found on a degree slope with extensive damage the airplane was reported missing and went undiscovered until august the airplane with human remains was discovered in a remote area of yosemite national park by trail repair personnel the faa and safety board did not have any records of the accident flight the registration number of the airplane had been reassigned to another aircraft in u s park and county sheriff s department personnel conducted a coroner s investigation
============================================================
Category   : Positive
Event ID   : 20001218X45448
Event Date : 1977-06-19
Narrative  : the aircraft wreckage was discovered miles south of the departure airport after having been missing for years a family member recalled that the non instrument rated pilot departed in marginal vfr conditions and stated his intent to fly south via a river and a highway the aircraft was last seen miles north of where the wreckage was found by the pilot of another aircraft that pilot reported the weather at the mountain valley location was to foot overcast with mountains obscured on both sides of the highway
============================================================

## Keyword Extraction

In [20]:
vectorizer = TfidfVectorizer(max_df=0.8, min_df=10, stop_words="english")
tfidf_matrix = vectorizer.fit_transform(df["analysis_clean"])
feature_names = vectorizer.get_feature_names_out()

In [21]:
# Get top words by average TF-IDF score
tfidf_mean = tfidf_matrix.mean(axis=0).A1
keywords = pd.DataFrame({"word": feature_names, "tfidf": tfidf_mean})
keywords.sort_values("tfidf", ascending=False).head(20)

             word     tfidf
333      airplane  0.068049
6847        pilot  0.059682
5243      landing  0.039301
3253       engine  0.038957
8128       runway  0.037438
3993         fuel  0.035504
3552      factual  0.032002
5329         left  0.030863
97           acft  0.030309
3804       flight  0.029862
312      aircraft  0.029725
4802  information  0.029092
7774     reported  0.027684
7974        right  0.027359
7052        power  0.026184
4075         gear  0.024776
58       accident  0.023350
3907      foreign  0.022452
6934          plt  0.022333
9016       stated  0.020720

## Topic Modeling

### BERT Topic

In [22]:
topic_model = BERTopic(language="english")
topics, probs = topic_model.fit_transform(df["analysis_clean"])

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=148857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
/home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=148857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=148857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=148857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages/joblib/externals/loky/backend/fork_exec.py:38: DeprecationWarning: This process (pid=148857) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [23]:
df["topic"] = topics
topic_info = topic_model.get_topic_info()
topic_info.head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,25639,-1_airplane_runway_pilot_and,"[airplane, runway, pilot, and, the, engine, to...",[the private pilot was conducting a personal c...
1,0,14350,0_acft_plt_rwy_flt,"[acft, plt, rwy, flt, eng, arpt, ft, aprx, apc...",[while on final apch to land at a private arpt...
2,1,6368,1_helicopter_rotor_tail_collective,"[helicopter, rotor, tail, collective, autorota...",[the helicopter pilot was lifting off with an ...
3,2,3774,2_student_instructor_solo_cfi,"[student, instructor, solo, cfi, runway, go, a...",[the flight instructor and student pilot were ...
4,3,3414,3_factual_same_information_as,"[factual, same, information, as, narrative, fo...","[same as factual information, same as factual ..."
5,4,2681,4_fuel_tank_gallons_tanks,"[fuel, tank, gallons, tanks, selector, engine,...",[the private pilot reported that when he depar...
6,5,1939,5_foreign___,"[foreign, , , , , , , , , ]","[foreign, foreign, foreign]"
7,6,1655,6_weather_instrument_radar_conditions,"[weather, instrument, radar, conditions, cloud...",[the pilot departed on a visual flight rules v...
8,7,1326,7_knots_wind_winds_degrees,"[knots, wind, winds, degrees, gusting, runway,...",[the pilot of the tailwheel equipped airplane ...
9,8,1171,8_oil_connecting_rod_crankshaft,"[oil, connecting, rod, crankshaft, engine, bea...",[the pilot receiving instruction reported that...

In [24]:
topic_info.shape, len(df)

((279, 5), 87951)

In [25]:
# Create topic mapping
topic_lookup = {}
for idx, row in topic_info.iterrows():
    topic, name = row['Topic'], row['Name']
    topic_lookup[topic] = name
topic_lookup

{-1: '-1_airplane_runway_pilot_and',
 0: '0_acft_plt_rwy_flt',
 1: '1_helicopter_rotor_tail_collective',
 2: '2_student_instructor_solo_cfi',
 3: '3_factual_same_information_as',
 4: '4_fuel_tank_gallons_tanks',
 5: '5_foreign___',
 6: '6_weather_instrument_radar_conditions',
 7: '7_knots_wind_winds_degrees',
 8: '8_oil_connecting_rod_crankshaft',
 9: '9_unk___',
 10: '10_glider_tow_plane_spoilers',
 11: '11_water_lake_float_floats',
 12: '12_snow_covered_ski_ice',
 13: '13_fire_smoke_exhaust_electrical',
 14: '14_lines_wires_wire_field',
 15: '15_carburetor_icing_heat_dew',
 16: '16_weight_gross_pounds_takeoff',
 17: '17_balloon_basket_envelope_passengers',
 18: '18_brake_brakes_tire_right',
 19: '19_tailwheel_equipped_preaccident_rudder',
 20: '20_bounced_nose_hard_firewall',
 21: '21_power_engine_loss_reason',
 22: '22_gear_main_strut_fracture',
 23: '23_ice_icing_conditions_rime',
 24: '24_magneto_magnetos_engine_spark',
 25: '25_water_fuel_contamination_gascolator',
 26: '26_probable_cause__',
 27: '27_turbulence_attendant_attendants_encounter',
 28: '28_valve_exhaust_cylinder_rocker',
 29: '29_taxiway_taxiing_truck_ramp',
 30: '30_propeller_blade_hub_fatigue',
 31: '31_certificated_tundra_tire_airstrip',
 32: '32_trim_elevator_tab_pitch',
 33: '33_witness_attitude_witnesses_nose',
 34: '34_approach_ils_localizer_missed',
 35: '35_deer_runway_wildlife_night',
 36: '36_gyroplane_rotor_blades_blade',
 37: '37_bird_birds_flock_strike',
 38: '38_throttle_cable_arm_linkage',
 39: '39_electrical_alternator_battery_gear',
 40: '40_canyon_terrain_rising_valley',
 41: '41_diphenhydramine_ml_blood_toxicology',
 42: '42_title_code_involved_regulations',
 43: '43_lights_night_lighting_runway',
 44: '44_alcohol_ethanol_blood_dl',
 45: '45_glider_tow_plt_rwy',
 46: '46_heart_coronary_medical_disease',
 47: '47_br___',
 48: '48_aerobatic_spin_maneuver_maneuvers',
 49: '49_student_fuel_country_gallons',
 50: '50_cessna_airplanes_traffic_collision',
 51: '51_factual___',
 52: '52_ultralight_vehicle_plt_flt',
 53: '53_gear_extend_retracted_landing',
 54: '54_grass_takeoff_fence_strip',
 55: '55_aileron_cable_control_ailerons',
 56: '56_carburetor_float_bowl_venturi',
 57: '57_gyrocopter_rotor_gyrocraft_blades',
 58: '58_ocean_ditched_sank_recovered',
 59: '59_canada_tsb_du_transportation',
 60: '60_marijuana_tetrahydrocannabinol_ml_ug',
 61: '61_banner_tow_pickup_hook',
 62: '62_spar_wing_corrosion_fatigue',
 63: '63_kingdom_united_aaib_branch',
 64: '64_horn_warning_gear_landing',
 65: '65_cylinder_number_field_cracked',
 66: '66_tug_pushback_driver_gate',
 67: '67_grass_wet_strip_airstrip',
 68: '68_piper_cessna_pa_airplanes',
 69: '69_brazil_cenipa_brazilian_prevention',
 70: '70_german_germany_bfu_obtained',
 71: '71_africa_south_civil_african',
 72: '72_propeller_engine_thrust_engines',
 73: '73_canopy_latch_opened_latching',
 74: '74_flaps_flap_full_go',
 75: '75_parachute_powered_aircraft_ppc',
 76: '76_pump_boost_electric_fuel',
 77: '77_has_ntsb_aaib_appointed',
 78: '78_sun_glare_blinded_eyes',
 79: '79_cessna_taxiway_taxi_taxiing',
 80: '80_crosswind_component_knots_demonstrated',
 81: '81_hand_start_started_propping',
 82: '82_mexico_de_dgac_general',
 83: '83_france_bourget_french_bea',
 84: '84_search_missing_michigan_presumed',
 85: '85_canyon_terrain_mountain_site',
 86: '86_trees_tree_end_airstrip',
 87: '87_nlg_mount_sb_cracks',
 88: '88_hydraulic_gear_fluid_extend',
 89: '89_door_cabin_cargo_locking',
 90: '90_beach_sand_soft_nosed',
 91: '91_pa_piper_aircraft_cessna',
 92: '92_nose_gear_bolt_collapsed',
 93: '93_australia_australian_atsb_au',
 94: '94_colombia_de_colombian_hk',
 95: '95_end_runway_foot_too',
 96: '96_taxi_speed_airborne_high',
 97: '97_gravel_bar_directional_causing',
 98: '98_lc_controller_eagle_tower',
 99: '99_gate_taxiway_ramp_crew',
 100: '100_stolen_owner_police_enforcement',
 101: '101_flare_knots_wind_gusting',
 102: '102_gear_green_light_locked',
 103: '103_atsb_australia_has_ntsb',
 104: '104_parachute_parachutist_jump_jumpers',
 105: '105_start_propeller_switch_hand',
 106: '106_hobbs_meter_gallons_hours',
 107: '107_china_korea_republic_railway',
 108: '108_rod_connecting_number_failed',
 109: '109_spain_de_ciaiac_fomento',
 110: '110_mixture_cable_control_arm',
 111: '111_looped_directional_loop_main',
 112: '112_russia_mak_russian_committee',
 113: '113_propeller_witness_fire_impact',
 114: '114_cowling_cowl_latch_latches',
 115: '115_steering_nosewheel_nose_wheel',
 116: '116_mexico_government_has_ntsb',
 117: '117_failures_malfunctions_sustained_precluded',
 118: '118_dust_devil_devils_encountered',
 119: '119_government_has_ntsb_indonesia',
 120: '120_publictn_ntsb_htm_aar',
 121: '121_aaib_kingdom_branch_united',
 122: '122_brazil_government_has_ntsb',
 123: '123_canada_tsb_has_ntsb',
 124: '124_pitot_indicator_airspeed_tube',
 125: '125_shimmy_nose_wheel_nosewheel',
 126: '126_seat_locking_pin_rail',
 127: '127_gear_landing_main_locked',
 128: '128_agricultural_field_loss_rice',
 129: '129_ecuador_de_ecuadorian_quito',
 130: '130_propeller_governor_rpm_drive',
 131: '131_italy_volo_nazionale_agenzia',
 132: '132_norway_swedish_sweden_se',
 133: '133_directional_looped_lost_control',
 134: '134_ultralight_vehicle_unregistered_exemption',
 135: '135_brake_fire_taxi_brakes',
 136: '136_lock_column_control_gust',
 137: '137_fa_turbulence_fas_attendant',
 138: '138_servo_flow_fuel_diaphragm',
 139: '139_unicom_winds_knots_wind',
 140: '140_compressor_turbine_blades_blade',
 141: '141_windshield_window_glass_moisture',
 142: '142_peru_de_ciaa_peruvian',
 143: '143_venezuela_de_caracas_venezuelan',
 144: '144_braking_thrust_runway_captain',
 145: '145_indonesia_transportation_dephub_knkt',
 146: '146_colombia_has_government_ntsb',
 147: '147_biplane_tailwheel_preaccident_substantial',
 148: '148_ruddervators_ruddervator_fs_bulkhead',
 149: '149_stage_lpt_turbine_disk',
 150: '150_supercharger_impeller_blower_forced',
 151: '151_gear_nose_locked_wow',
 152: '152_india_airbus_government_turbofan',
 153: '153_cfi_fuel_tank_instructor',
 154: '154_gear_actuator_main_locked',
 155: '155_instructor_tailwheel_rudder_owner',
 156: '156_bahamas_nassau_bahamian_jamaica',
 157: '157_door_baggage_latch_opened',
 158: '158_directional_veered_runway_touchdown',
 159: '159_beach_water_ocean_surf',
 160: '160_australia_atsb_australian_vh',
 161: '161_brakes_nosed_applied_brake',
 162: '162_corn_grass_tall_airstrip',
 163: '163_rv_bama_formation_lead',
 164: '164_knots_snow_snowbank_wind',
 165: '165_peru_ciaa_de_has',
 166: '166_nut_fitting_loose_pump',
 167: '167_gyro_vacuum_indicator_attitude',
 168: '168_spark_plug_helicoil_cylinder',
 169: '169_sink_rate_high_short',
 170: '170_airstrip_preaccident_malfunctions_brush',
 171: '171_trike_shift_weight_bar',
 172: '172_chile_chilean_providencia_blanco',
 173: '173_aborted_takeoff_abort_end',
 174: '174_dgac_mexico_has_ntsb',
 175: '175_italy_ansv_has_ntsb',
 176: '176_fuel_tank_carburetor_tanks',
 177: '177_bfu_germany_german_has',
 178: '178_ils_approach_missed_glideslope',
 179: '179_aaiu_ireland_has_ntsb',
 180: '180_government_ecuador_chile_has',
 181: '181_suicide_death_manner_wife',
 182: '182_cable_rudder_pulley_cables',
 183: '183_flare_ballooned_wind_wing',
 184: '184_japan_tokyo_jtsb_kasumigaseki',
 185: '185_united_kingdom_government_has',
 186: '186_jtsb_japan_has_ntsb',
 187: '187_trees_pic_wind_pole',
 188: '188_brazil_cenipa_brazilian_prevention',
 189: '189_coyote_coyotes_gunner_trainee',
 190: '190_argentina_de_buenos_aires',
 191: '191_france_government_has_ntsb',
 192: '192_cfr_title_part_wing',
 193: '193_ditched_ditching_restart_hours',
 194: '194_import___',
 195: '195_none___',
 196: '196_rudder_yaw_pedals_solenoids',
 197: '197_walked_passenger_propeller_she',
 198: '198_propeller_feather_feathered_feathering',
 199: '199_flap_instead_flaps_inadvertently',
 200: '200_induction_coupling_tube_stoppage',
 201: '201_pitts_cessna_taxiing_show',
 202: '202_rudder_right_veered_left',
 203: '203_guatemala_guatemalan_aurora_zona',
 204: '204_gps_data_track_stall',
 205: '205_gear_pivot_main_landing',
 206: '206_lightning_airship_rain_thunderstorms',
 207: '207_atsb_australia_australian_au',
 208: '208_cruise_tanks_fuel_forced',
 209: '209_swath_run_field_spray',
 210: '210_aileron_touchdown_runway_right',
 211: '211_autopilot_engaged_trim_engagement',
 212: '212_wsc_experience_experimental_aerodynamic',
 213: '213_heat_carburetor_rows_power',
 214: '214_argentina_jiaac_has_ntsb',
 215: '215_power_fuel_loss_forced',
 216: '216_crosswind_sailboat_sail_hangars',
 217: '217_probable_cause__',
 218: '218_flap_roller_inboard_hinge',
 219: '219_poland_commission_republic_czech',
 220: '220_turkey_turkish_tc_ankara',
 221: '221_crosswind_rudder_loop_runway',
 222: '222_oxygen_hypoxia_pressurization_mask',
 223: '223_truck_trailer_road_driver',
 224: '224_wreckage_witnesses_witness_continuity',
 225: '225_highway_road_driveway_gravel',
 226: '226_trees_airstrip_pine_aircraft',
 227: '227_preaccident_malfunctions_sustained_substantial',
 228: '228_fan_blade_tai_dovetail',
 229: '229_germany_government_has_ntsb',
 230: '230_tcas_ra_gpws_traffic',
 231: '231_seller_buyer_propeller_fire',
 232: '232_looped_directional_crosswind_control',
 233: '233_spin_spins_recovery_revolutions',
 234: '234_nose_runway_bounced_too',
 235: '235_knkt_indonesia_has_ntsb',
 236: '236_gcaa_emirates_arab_has',
 237: '237_zealand_new_taic_wellington',
 238: '238_preliminary___',
 239: '239_soft_nosed_sod_over',
 240: '240_substance_carburetor_screen_bowl',
 241: '241_wasp_vent_nest_insect',
 242: '242_witness_witnesses_trees_wreckage',
 243: '243_grass_airstrip_nosed_stabilizer',
 244: '244_spain_government_has_ntsb',
 245: '245_her_she_passenger_stairs',
 246: '246_crosswind_aircraft_sandy_airlanes',
 247: '247_hangar_roof_wind_knots',
 248: '248_creek_developing_takeoff_initial',
 249: '249_coronary_disease_artery_heart',
 250: '250_video_witness_sound_likely',
 251: '251_student_fef_abx_phone',
 252: '252_plane_drift_left_private',
 253: '253_sic_pic_command_reversers',
 254: '254_captain_parking_officer_spoiler',
 255: '255_sacaa_african_has_ntsb',
 256: '256_brazil_government_has_ntsb',
 257: '257_caa_has_ntsb_africa',
 258: '258_methamphetamine_blood_urine_drug',
 259: '259_aaib_kingdom_uk_has',
 260: '260_elt_search_signal_wreckage',
 261: '261_brazil_brazilian_cenipa_paulo',
 262: '262_india_delhi_dgca_safdarjung',
 263: '263_bounced_wing_veered_runway',
 264: '264_fuel_tank_totalizer_witness',
 265: '265_rudder_applied_veered_jerked',
 266: '266_jumper_looped_inflated_exited',
 267: '267____',
 268: '268_tower_antenna_guy_wire',
 269: '269_rough_running_fouled_roughness',
 270: '270_firewall_damage_discovered_inspection',
 271: '271_thrust_reverse_reverser_levers',
 272: '272_forced_shutoff_experienced_lose',
 273: '273_mak_has_ntsb_committee',
 274: '274_selector_fuel_quantity_tank',
 275: '275_ciaiac_de_has_ntsb',
 276: '276_stcs_stall_flap_aerodynamic',
 277: '277_plug_carburetor_contamination_drain'}

In [26]:
df['topic_name'] = df['topic'].apply(lambda x: topic_lookup[x])

**Observation:** `BERTopic` created `285` unique categories using `87,951` reports. The top three categories are:
1) Airplanes, runways, and pilots at `24,304` reports
2) ACFT (Aircraft), PLT (Pilot), RWY (Runway), and FLT (Flight) at `14,311` reports
3) Helicopter, Rotor, Tail, and Collective at `6,362` reports.

Expanding acronyms would improve the richness of the topics as we can tell from the second category being composed of all acronyms. It's interesting that the 3rd category appears to have separated out all rotocraft related reports which is pretty nice.

### LDA with Visualization (Gensim)

In [27]:
# lda_results = group_topics_lda(
#     data=df['analysis_clean']
# )

## Export Dataset
Exporting for ingest into visualization applications such as Power BI.

In [28]:
df.columns

Index(['event_id', 'event_date', 'investigation_type', 'country',
       'aircraft_damage', 'aircraft_category', 'make', 'model',
       'amateur_built', 'number_of_engines', 'engine_type', 'far_description',
       'schedule', 'purpose_of_flight', 'total_fatal_injuries',
       'total_serious_injuries', 'total_minor_injuries', 'total_uninjured',
       'weather_condition', 'broad_phase_of_flight', 'analysis',
       'analysis_clean', 'analysis_preprocessed', 'city', 'longitude',
       'latitude', 'address', 'geometry', 'place', 'number_of_seats',
       'type_aircraft', 'type_engine', 'total_person',
       'far_description_factorized', 'schedule_factorized',
       'purpose_of_flight_factorized', 'make_factorized', 'model_factorized',
       'year', 'publication_year', 'month', 'publication_month', 'day',
       'publication_day', 'date_difference', 'publication_month_name',
       'event_month_name', 'season', 'sentiment_polarity',
       'sentiment_category', 'topic', 'topic_name'],
      dtype='object')

In [29]:
df.to_csv("../data/enriched_ntsb_nlp.csv", index=False)

In [30]:
topic_info.to_csv('../data/ntsb_topic_info.csv', index=False)

In [31]:
# Create a zip archive containing the enriched dataset and topic info
import zipfile
import os

output_zip = '../data/ntsb_nlp_results.zip'

with zipfile.ZipFile(output_zip, 'w') as zf:
    zf.write('../data/enriched_ntsb_nlp.csv', os.path.basename('../data/enriched_ntsb_nlp.csv'))
    zf.write('../data/ntsb_topic_info.csv', os.path.basename('../data/ntsb_topic_info.csv'))

print(f'Created zip archive: {output_zip}')

Created zip archive: ../data/ntsb_nlp_results.zip