# Preprocessing Data for NLP Tasks

## Setup

In [2]:
!python --version

Python 3.12.4

In [3]:
!python -m pip install -q pandas numpy matplotlib seaborn wordcloud nltk spacy textblob scikit-learn bertopic

In [4]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 27.0 MB/s eta 0:00:0031m28.7 MB/s eta 0:00:01
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from en-core-web-sm==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.66.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.11.7)
Requirement already satisfied: jinja2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.1.5)
Requirement already satisfied: setuptools in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (75.4.0)
Requirement already satisfied: packaging>=20.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.12.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2024.7.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (13.6.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.16.1)
Requirement already satisfied: wrapt in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /home/ballen/anaconda3/envs/data-science/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.2)
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

### Imports

In [5]:
from textblob import TextBlob
import pandas as pd

### Configurations

In [6]:
data_path = '../data/cleaned_ntsb.csv'

In [7]:
pd.set_option('display.max_columns', None)

## Load Data

In [8]:
df = pd.read_csv(data_path, low_memory=False)
df.shape

(87951, 47)

In [9]:
df.head()

,event_id,event_date,investigation_type,country,aircraft_damage,aircraft_category,make,model,amateur_built,number_of_engines,engine_type,far_description,schedule,purpose_of_flight,total_fatal_injuries,total_serious_injuries,total_minor_injuries,total_uninjured,weather_condition,broad_phase_of_flight,analysis,analysis_clean,city,longitude,latitude,address,geometry,place,number_of_seats,type_aircraft,type_engine,total_person,far_description_factorized,schedule_factorized,purpose_of_flight_factorized,make_factorized,model_factorized,year,publication_year,month,publication_month,day,publication_day,date_difference,publication_month_name,event_month_name,season
0,20001218X45444,1948-10-24,Accident,United States,Destroyed,fixed wing single engine,stinson,108-3,No,1,reciprocating,part 91: general aviation,UNK,Personal,2,0,0,0,UNK,Cruise,"ON OCTOBER 24, 1948, THE PILOT DEPARTED A PRIV...",on october the pilot departed a private airstr...,moose creek,-147.160665,64.713512,"Moose Creek, Fairbanks North Star, Alaska, Uni...",POINT (-147.1606646266588 64.7135123),mountain,4,4,1,2,1,2,0,0,0,1948,2001,10,8,24,24.0,26,August,October,Fall
1,20001218X45447,1962-07-19,Accident,United States,Destroyed,weight-shift-control,piper,pa24-180,No,1,reciprocating,part 91: general aviation,UNK,Personal,4,0,0,0,UNK,Unknown,"ON JULY 19, 1962, A COMMERCIAL, NON-INSTRUMENT...",on july a commercial non instrument rated pilo...,bridgeport,-73.188786,41.179269,"Bridgeport, Greater Bridgeport Planning Region...",POINT (-73.1887863 41.1792695),sea,4,7,1,4,1,2,0,1,1,1962,1996,7,9,19,19.0,34,September,July,Summer
2,20061025X01555,1974-08-30,Accident,United States,Destroyed,fixed wing single engine,cessna,172m,No,1,reciprocating,part 91: general aviation,UNK,Personal,3,0,0,1,IMC,Cruise,The private pilot was issued his certificate o...,the private pilot was issued his certificate o...,saltville,-81.762063,36.881503,"Saltville, Smyth County, Virginia, United States",POINT (-81.7620635 36.8815031),sea,4,4,1,3,1,2,0,2,2,1974,2007,8,2,30,30.0,33,February,August,Summer
3,20001218X45448,1977-06-19,Accident,United States,Destroyed,weight-shift-control,rockwell,112,No,1,reciprocating,part 91: general aviation,UNK,Personal,2,0,0,0,IMC,Cruise,The aircraft wreckage was discovered 22 miles ...,the aircraft wreckage was discovered miles sou...,eureka,-124.167375,40.790687,"Eureka, Humboldt County, California, United St...",POINT (-124.1673746 40.7906871),airport,4,7,1,2,1,2,0,3,3,1977,2000,6,12,19,19.0,23,December,June,Summer
4,20041105X01764,1979-08-02,Accident,United States,Destroyed,fixed wing multi engine,cessna,501,No,2,turbo fan,part 91: general aviation,UNK,Personal,1,2,0,0,VMC,Approach,The Safety Board's full report is available at...,the safety board s full report is available at...,canton,-95.864051,32.555664,"Canton, Van Zandt County, Texas, 75103, United...",POINT (-95.8640507 32.555664),airport,8,5,5,3,1,2,0,2,4,1979,1980,8,4,2,2.0,1,April,August,Summer

## Sentiment Analysis

In [10]:
df["sentiment_polarity"] = df["analysis_clean"].apply(lambda x: TextBlob(x).sentiment.polarity)
df["sentiment_category"] = pd.cut(
    df["sentiment_polarity"],
    bins=[-1, -0.05, 0.05, 1],
    labels=["Negative", "Neutral", "Positive"]
)

In [15]:
df[["analysis_clean", "sentiment_polarity", "sentiment_category"]].sample(50, random_state=42)

,analysis_clean,sentiment_polarity,sentiment_category
25609,witnesses observed the acft maneuvering at a l...,-0.019136,Neutral
31738,factual,0.000000,Neutral
5346,after takeoff the plt of the ultralight vehicl...,0.020833,Neutral
85707,the pilot had made two flights on the day of t...,0.024351,Neutral
59785,the airplane was flown by the student and cert...,0.024451,Neutral
22491,the plt landed in a field which he knew contai...,0.214286,Positive
25703,the pilot was landing and bounced twice he rej...,0.158929,Positive
7492,the plt angled in on the final approach at low...,0.095238,Positive
64569,same as factual information,0.000000,Neutral
4293,the pilot was warming the eng for a compressio...,0.037143,Neutral
73557,same as factual information,0.000000,Neutral
1815,before departing st louis mo attempts to resta...,-0.058333,Negative
62735,on october a us airways boeing n uw experience...,0.010777,Neutral
78452,the pilot reported that while on final approac...,0.002778,Neutral
56715,according to the pilot during the take off rol...,0.043386,Neutral
81664,the pilot of the tailwheel equipped airplane r...,-0.033929,Neutral
37925,during departure upon reaching feet altitude a...,0.150000,Positive
35077,the pilot reported he was about feet agl when ...,-0.333333,Negative
11728,the plt was making an apch to rwy at the los a...,0.359524,Positive
59957,same as factual information,0.000000,Neutral
28081,while on final approach to a dirt road the pil...,-0.031111,Neutral
36233,at cst on the helicopter took off on a flight ...,-0.072917,Negative
84407,the pilot completed a multi day cross country ...,-0.085873,Negative
50695,foreign,-0.125000,Negative
86669,unk,0.000000,Neutral
36567,the four engine transport category airplane wa...,0.012778,Neutral
87546,on september about pacific daylight time a bee...,0.046155,Neutral
43431,the hour instrument rated commercial helicopte...,-0.064140,Negative
48767,foreign,-0.125000,Negative
87840,the pilot of the tailwheel equipped airplane r...,0.050265,Positive
21130,the commercial plt was transporting one pax du...,-0.125000,Negative
78511,the government of united kingdom has notified ...,0.000000,Neutral
70454,on february about pacific standard time a euro...,0.010000,Neutral
31287,cattle missed by men on horseback would be spo...,0.000000,Neutral
74855,the pilot reported that he landed the airplane...,-0.007864,Neutral
86949,the pilot reported that after a normal approac...,0.192857,Positive
76342,the australian transport safety bureau atsb ha...,0.000000,Neutral
1543,the pilot reported that he had landed long in ...,0.050000,Positive
37521,the engine sustained a total loss of power at ...,-0.109375,Negative
15910,the pilot was cleared to taxi his airplane int...,0.042857,Neutral
77029,same as factual information,0.000000,Neutral
77045,same as factual information,0.000000,Neutral
63505,the commercial rated pilot was practicing a st...,-0.062500,Negative
77488,same as factual information,0.000000,Neutral
69712,at the conclusion of the pilot s second flight...,0.102679,Positive
57553,according to the pilot during the completion o...,-0.170000,Negative
61962,the instrument rated private pilot departed on...,-0.060000,Negative
40556,the gcbc champion was observed engaged in repe...,0.191446,Positive
69314,the helicopter pilot landed a high skid turbin...,-0.049596,Neutral
43295,while troubleshooting a fire warning indicatio...,0.180000,Positive